apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hrg9e5rd5-python
  janus-idp.io/tekton: hrg9e5rd5-python
  backstage.io/kubernetes-id: hrg9e5rd5-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hrg9e5rd5-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
